name: Deploy SSHX

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSHX
        run: |
          curl -sSf https://sshx.io/get | sh -s run
